import {  MovimientosDinero } from '../interface/iDatabaseMovments';

export const Movimientos:MovimientosDinero  = {
    'movimientos': [
        {
            'id': 1,
            'fecha': '2021-10-01',
            'descripcion': 'Pago de servicios',
            'monto': 1000,
            'tipo': 'deposito',
            'status': 'pendiente',
            'nombre':'Wise',
        },
        {
            'id': 2,
            'fecha': '2021-10-02',
            'descripcion': 'Pago de servicios',
            'monto': 50,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 3,
            'fecha': '2021-10-03',
            'descripcion': 'Pago de servicios',
            'monto': 100,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 4,
            'fecha': '2021-11-03',
            'descripcion': 'Pago de servicios',
            'monto': 200,
            'tipo': 'deposito',
            'status': 'cancelado',
            'nombre':'Wise',
        },
        {
            'id': 5,
            'fecha': '2021-15-03',
            'descripcion': 'Pago de servicios',
            'monto': 10,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 6,
            'fecha': '2021-11-03',
            'descripcion': 'Pago de servicios',
            'monto': 100,
            'tipo': 'deposito',
            'status': 'cancelado',
            'nombre':'Wise',
        },
        {
            'id': 7,
            'fecha': '2021-15-03',
            'descripcion': 'Pago de servicios',
            'monto': 200,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 8,
            'fecha': '2021-15-03',
            'descripcion': 'Pago de servicios',
            'monto': 500,
            'tipo': 'deposito',
            'status': 'cancelado',
            'nombre':'Wise',
        },
        {
            'id': 9,
            'fecha': '2021-15-03',
            'descripcion': 'Pago de servicios',
            'monto': 120,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 10,
            'fecha': '2021-16-03',
            'descripcion': 'Pago de servicios',
            'monto': 1110,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 11,
            'fecha': '2021-16-03',
            'descripcion': 'Pago de servicios',
            'monto': 1110,
            'tipo': 'deposito',
            'status': 'completado',
            'nombre':'Wise',
        },
        {
            'id': 12,
            'fecha': '2021-16-03',
            'descripcion': 'Pago de servicios',
            'monto': 10,
            'tipo': 'deposito',
            'status': 'cancelado',
            'nombre':'Wise',
        },
    ],
};
